name: causal-method-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.11
  - pip
  # ensures right compiler for cython
  - c-compiler
  - cxx-compiler
  - pip:
      - -r requirements.txt